I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 327, in script
    young_gg "А что я должен понимать?"
Exception: Sayer 'young_gg' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 327, in script
    young_gg "А что я должен понимать?"
  File "C:\Users\Alexander\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Alexander\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'young_gg' is not defined.

Windows-10-10.0.17763 AMD64
Ren'Py 8.0.3.22090809
Rebirth 1.0
Wed Nov 16 23:17:43 2022
